### ISSUE TITLE
CA certificate loading errors

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-push-server#909]
Following error occurs in Push Server:

```
2024-11-18T12:36:34.447+01:00 ERROR 707851 --- [powerauth-java-server] [Pool-worker-343] [                                                 ] io.getlime.push.util.CaCertUtil          : Certificate error: class path resource [cacert/USERTrustRSAAAACA.pem] cannot be opened because it does not exist

java.io.FileNotFoundException: class path resource [cacert/USERTrustRSAAAACA.pem] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:215)
	at io.getlime.push.util.CaCertUtil.allCerts(CaCertUtil.java:95)
	at io.getlime.push.service.PushSendingWorker.prepareApnsClient(PushSendingWorker.java:428)
	at io.getlime.push.service.AppRelatedPushClientCacheLoader.createPushClient(AppRelatedPushClientCacheLoader.java:97)
	at io.getlime.push.service.AppRelatedPushClientCacheLoader.reload(AppRelatedPushClientCacheLoader.java:72)
	at io.getlime.push.service.AppRelatedPushClientCacheLoader.reload(AppRelatedPushClientCacheLoader.java:39)
	at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncReload$2(CacheLoader.java:196)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by banterCZ** [comment]
Introduced via #801

**Comment by romanstrobl** [comment]
Issue cannot be reproduced after application server restart.
